In [1]:
import pandas as pd

In [2]:
#importing dataset

df = pd.read_csv('test.csv')
df.head()

Employee ID  Age Gender  Years at Company    Job Role  Monthly Income  \
0        52685   36   Male                13  Healthcare            8029   
1        30585   35   Male                 7   Education            4563   
2        54656   50   Male                 7   Education            5583   
3        33442   58   Male                44       Media            5525   
4        15667   39   Male                24   Education            4604   

  Work-Life Balance Job Satisfaction Performance Rating  Number of Promotions  \
0         Excellent             High            Average                     1   
1              Good             High            Average                     1   
2              Fair             High            Average                     3   
3              Fair        Very High               High                     0   
4              Good             High            Average                     0   

   ... Number of Dependents  Job Level Company Size Company Tenure  \
0  ...                    1        Mid        Large             22   
1  ...                    4      Entry       Medium             27   
2  ...                    2     Senior       Medium             76   
3  ...                    4      Entry       Medium             96   
4  ...                    6        Mid        Large             45   

   Remote Work Leadership Opportunities Innovation Opportunities  \
0           No                       No                       No   
1           No                       No                       No   
2           No                       No                      Yes   
3           No                       No                       No   
4          Yes                       No                       No   

   Company Reputation Employee Recognition Attrition  
0                Poor               Medium    Stayed  
1                Good                 High      Left  
2                Good                  Low    Stayed  
3                Poor                  Low      Left  
4                Good                 High    Stayed  

[5 rows x 24 columns]

In [3]:
#Sorting column name
df.columns = df.columns.str.lower().str.replace(' ','_')
df.head()

employee_id  age gender  years_at_company    job_role  monthly_income  \
0        52685   36   Male                13  Healthcare            8029   
1        30585   35   Male                 7   Education            4563   
2        54656   50   Male                 7   Education            5583   
3        33442   58   Male                44       Media            5525   
4        15667   39   Male                24   Education            4604   

  work-life_balance job_satisfaction performance_rating  number_of_promotions  \
0         Excellent             High            Average                     1   
1              Good             High            Average                     1   
2              Fair             High            Average                     3   
3              Fair        Very High               High                     0   
4              Good             High            Average                     0   

   ... number_of_dependents  job_level company_size company_tenure  \
0  ...                    1        Mid        Large             22   
1  ...                    4      Entry       Medium             27   
2  ...                    2     Senior       Medium             76   
3  ...                    4      Entry       Medium             96   
4  ...                    6        Mid        Large             45   

   remote_work leadership_opportunities innovation_opportunities  \
0           No                       No                       No   
1           No                       No                       No   
2           No                       No                      Yes   
3           No                       No                       No   
4          Yes                       No                       No   

   company_reputation employee_recognition attrition  
0                Poor               Medium    Stayed  
1                Good                 High      Left  
2                Good                  Low    Stayed  
3                Poor                  Low      Left  
4                Good                 High    Stayed  

[5 rows x 24 columns]

In [4]:
#handling Null, Duplicates,  values
df.isnull().sum()          #No Null values
df.duplicated().sum()      #No Duplicates values

np.int64(0)

In [5]:
#dataype inspection
df.dtypes

employee_id                  int64
age                          int64
gender                      object
years_at_company             int64
job_role                    object
monthly_income               int64
work-life_balance           object
job_satisfaction            object
performance_rating          object
number_of_promotions         int64
overtime                    object
distance_from_home           int64
education_level             object
marital_status              object
number_of_dependents         int64
job_level                   object
company_size                object
company_tenure               int64
remote_work                 object
leadership_opportunities    object
innovation_opportunities    object
company_reputation          object
employee_recognition        object
attrition                   object
dtype: object

In [6]:
#checking for Inconsistencies in dataframe
for col in df.select_dtypes(include='object').columns:
    print(f"{col}: {df[col].unique()}")

gender: ['Male' 'Female']
job_role: ['Healthcare' 'Education' 'Media' 'Technology' 'Finance']
work-life_balance: ['Excellent' 'Good' 'Fair' 'Poor']
job_satisfaction: ['High' 'Very High' 'Medium' 'Low']
performance_rating: ['Average' 'High' 'Below Average' 'Low']
overtime: ['Yes' 'No']
education_level: ['Master’s Degree' 'Associate Degree' 'High School' 'Bachelor’s Degree'
 'PhD']
marital_status: ['Married' 'Single' 'Divorced']
job_level: ['Mid' 'Entry' 'Senior']
company_size: ['Large' 'Medium' 'Small']
remote_work: ['No' 'Yes']
leadership_opportunities: ['No' 'Yes']
innovation_opportunities: ['No' 'Yes']
company_reputation: ['Poor' 'Good' 'Fair' 'Excellent']
employee_recognition: ['Medium' 'High' 'Low' 'Very High']
attrition: ['Stayed' 'Left']


In [ ]:
#checking for uniquw values in Job Satisfaction
print(df['job_satisfaction'].unique())

['High' 'Very High' 'Medium' 'Low']


In [ ]:
#Formatting everything
df['job_satisfaction'] = df['job_satisfaction'].str.strip().str.title()

In [ ]:
#reaaplying Mapping to Job Satishfaction
df['job_satisfaction'] = df['job_satisfaction'].map({
    'Low': 1, 'Medium': 2, 'High': 3, 'Very High': 4
})

In [ ]:
#Checking for Values
print(df['job_satisfaction'].unique())

[3 4 2 1]


In [ ]:
#final verification of Job Satisfaction
print(df['job_satisfaction'].isna().sum())

print(df['job_satisfaction'].unique())

0
[3 4 2 1]


In [ ]:
#Converting Strings to Numerical value for better Visualization column by column

#work_life_balance
df['work-life_balance'] = df['work-life_balance'].map({
    'Poor': 1,
    'Fair': 2,
    'Good': 3,
    'Excellent': 4
})

#performance_rating
df['performance_rating'] = df['performance_rating'].map({
    'Low': 1,
    'Below Average': 2,
    'Average': 3,
    'High': 4
})

#employee_recognition
df['employee_recognition'] = df['employee_recognition'].map({
    'Low': 1,
    'Medium': 2,
    'High': 3,
    'Very High':4
})

#company_reputation
df['company_reputation'] = df['company_reputation'].map({
    'Poor': 1,
    'Fair': 2,
    'Good': 3,
    'Excellent': 4
})

In [ ]:
#cehcking mapping in applied column

print(df['job_satisfaction'].unique())
print(df['work-life_balance'].unique())
print(df['performance_rating'].unique())
print(df['employee_recognition'].unique())
print(df['company_reputation'].unique())

[3 4 2 1]
[4 3 2 1]
[3 4 2 1]
[2 3 1 4]
[1 3 2 4]


In [25]:
df.to_csv('cleaned_data.csv', index=False)
print("downloaded newly updated cs:")

downloaded newly updated cs:
